---
volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: ninocan/vote:latest
    ports:
      - 5005:80
    depends_on:
      - redis
    networks:
      - instavote

  result:
    image: ninocan/result:latest
    ports:
      - 5001:4000
    networks:
      - instavote

  worker:
    image: ninocan/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - instavote
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  # deploy:
  #   resources:
  #     limits:
  #       cpus: '0.50'
  #       memory: 3G
  #     reservations:
  #       cpus: '0.50'
  #       memory: 3G

  redis:
    image: redis:alpine

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
